kumuluzee:
  name: priority-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8087
    http:
      port: 8087
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15
  logs:
    config-file:
      '<?xml version="1.0" encoding="UTF-8"?>
       <Configuration name="tutorial-logging">
           <Appenders>
               <Console name="console" target="SYSTEM_OUT">
                   <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
               </Console>

               <!-- A socket definition for sending logs into Logstash using TCP and JSON format.-->
               <Socket name="logstash" host="7a65968c-f49f-4ea9-858e-593493242e63-ls.logit.io" port="17725" protocol="tcp">
                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
               </Socket>

           </Appenders>
           <Loggers>
               <!-- Default logger -->
               <Root level="trace">
                   <!--<AppenderRef ref="console"/>-->
                   <AppenderRef ref="logstash"/>
               </Root>
           </Loggers>
       </Configuration>'


rest-properties:
  external-dependencies:
    priority-service:
      registration-enabled: true